const Images = [
  { image: require("../images/clothing/clothes1.jpg") },
  { image: require("../images/clothing/clothes2.jpeg") },
  { image: require("../images/clothing/clothes3.jpg") },
  { image: require("../images/clothing/clothes1.jpg") },
];

export const items = [
  {
    id_shop: 1,
    id_prod: 1,
    name: "T-Shirt",
    price: "200",
    description: "Made from cotton",
    image: Images[0].image,
  },
  {
    id_shop: 1,
    id_prod: 2,
    name: "Adidas Addidas",
    price: "130",
    description: "Made from leather",
    image: Images[1].image,
  },
  {
    id_shop: 1,
    id_prod: 3,
    name: "Jacket",
    price: "500",
    description: "Made from leather",
    image: Images[2].image,
  },
  {
    id_shop: 1,
    id_prod: 4,
    name: "Mocasinos",
    price: "50000",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 2,
    id_prod: 1,
    name: "Macaroane",
    price: "50000",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 2,
    id_prod: 2,
    name: "Zumba",
    price: "50000",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 2,
    id_prod: 3,
    name: "Clothies",
    price: "523",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 2,
    id_prod: 4,
    name: "Rimba",
    price: "420",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 3,
    id_prod: 1,
    name: "Sera",
    price: "911",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 3,
    id_prod: 2,
    name: "Mike",
    price: "3536",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 3,
    id_prod: 3,
    name: "Tyson",
    price: "23",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 3,
    id_prod: 4,
    name: "Calvine Klane",
    price: "3213",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 3,
    id_prod: 5,
    name: "Cucii",
    price: "711",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 4,
    id_prod: 1,
    name: "Dihor",
    price: "6427",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 4,
    id_prod: 2,
    name: "Fakee",
    price: "48",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 4,
    id_prod: 3,
    name: "Yourdan",
    price: "929",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 4,
    id_prod: 4,
    name: "Eazzy",
    price: "5231",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 5,
    id_prod: 1,
    name: "Fuma",
    price: "45",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 5,
    id_prod: 2,
    name: "Supremacy",
    price: "468",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 5,
    id_prod: 3,
    name: "Bossy",
    price: "46531",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 5,
    id_prod: 4,
    name: "LecocSportyf",
    price: "3020",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 6,
    id_prod: 1,
    name: "Marco polo",
    price: "4650",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 6,
    id_prod: 2,
    name: "Louis PlankTon",
    price: "86932",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 6,
    id_prod: 3,
    name: "Crocks",
    price: "4650",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 6,
    id_prod: 4,
    name: "LaCostel",
    price: "2413",
    description: "Made from leather",
    image: Images[3].image,
  },
  {
    id_shop: 6,
    id_prod: 5,
    name: "Dolce&Banana",
    price: "829",
    description: "Made from leather",
    image: Images[3].image,
  },
];
